feat: add playwright monitoring to pipeline runner

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -24,7 +24,7 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: ">=22.14.0 22"
-      
+
       - name: Cache central NPM modules
         uses: actions/cache@v4
         with:
@@ -32,7 +32,7 @@ jobs:
           key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-
-      
+
       - name: Install dependencies
         run: |
           npm ci
@@ -42,7 +42,17 @@ jobs:
         run: npx playwright install --with-deps
 
       - name: Run Playwright tests
-        run: npm run test:ct -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
+        run: |
+          PLAYWRIGHT_JSON_OUTPUT_NAME=results.json
+          PW_OUTPUT_JSON=$(((npm run test:ct -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=json) 2>&1) || true)
+
+          # Check for incomplete tests
+          INCOMPLETE_TESTS=$(echo "$PW_OUTPUT_JSON" | jq '.entries[] | select(.result.status == "incomplete") | .result')
+
+          if [ -n "$INCOMPLETE_TESTS" ]; then
+            echo "::error::Detected incomplete tests:"
+            echo "$INCOMPLETE_TESTS" | jq .
+          fi
 
       - name: Upload blob report to Artifacts
         if: ${{ !cancelled() }}
